
::  Bat script for compilation of the rb_scope.dll using MSVS cl and link.
::  This script has been automatically generated by rake from the template in rakefile.rb.
::
::  author      hugo benichi
::  email       hugo.benichi@gmail.com
::  copyright   2012 hugo benichi

  call "C:\Program Files (x86)\MVS10.0\VC\vcvarsall.bat"

  call ruby -Ilib ext\ni_scope\wrapper_generator.rb > ext\ni_scope\wrapper.c

  call cl -c .\ext\ni_scope\wrapper.c -I"C:\Program Files (x86)\IVI Foundation\VISA\WinNT\include"  

  call link /DLL /OUT:ext\ni_scope\rb_scope.dll wrapper.obj "C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Lib\msc\niScope.lib" 
 