#!/usr/local/bin/ruby
# This script will extract the NAME VALUE pairs file generated by extract_names.rb
# extract_names.rb and the gcc preprocessor and sligthly reformats the pairs in
# order for ruby to be able to process them as eval strings.
#
# call with extract.rb scope.h filtered_scope.

output = ARGV[1] ? File.open(ARGV[1], "w") : $stdout

File.open(ARGV[0],'r').readlines.select{ |line|
    line =~ /^"[\w]+";/
}.each{ |line|
    output.puts line.gsub("L)",")").gsub(/(\d)L/,"\\1").sub(/^"([\w]+)"; /, "\\1\n") [0..-3]
}

output.close unless output == $stdin
